# frozen_string_literal: true
require "rails"
require "kamigo/version"
require "kamigo/event"
require "kamigo/router"
require "kamigo/dispatcher"
require "kamigo/engine"
require "kamiflex"
require "kamiliff"
require "kamigo/controller"
require "kamigo/agent"
require "kamigo/identity"
require "kamigo/platforms/line"
require "kamigo/platforms/telegram"
require "kamigo/rendering/renderer"
require "kamigo/reliability"
require "kamigo/platforms/http_transport"
